create table public.account (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  name text not null,
  constraint account_pkey primary key (id),
  constraint account_user_id_id_key unique (user_id, id),
  constraint account_user_id_name_key unique (user_id, name),
  constraint account_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;