create table public.budget_type (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  name text not null,
  icon text null,
  constraint budget_type_pkey primary key (id),
  constraint budget_type_user_id_id_key unique (user_id, id),
  constraint budget_type_user_id_name_key unique (user_id, name),
  constraint budget_type_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;