create table public.main_category (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  label text not null,
  icon text not null,
  back_color text not null,
  fore_color text not null,
  transaction_type public.transaction_type not null,
  constraint main_category_pkey primary key (id),
  constraint main_category_user_id_id_key unique (user_id, id),
  constraint main_category_user_id_transaction_type_label_key unique (user_id, transaction_type, label),
  constraint main_category_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists main_category_user_id_transaction_type_idx on public.main_category using btree (user_id, transaction_type) TABLESPACE pg_default;
