create table public.matching_rule (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  
  -- 过滤条件字段
  f_original_amount_ge numeric(18, 2) null,
  f_original_amount_le numeric(18, 2) null,
  f_time text null,
  f_title text not null,
  
  -- 目标赋值字段
  t_tx_type public.transaction_type null,
  t_main_category_id bigint null,
  t_sub_category_id bigint null,
  t_budget_type_id bigint null,
  t_name text null,
  t_merchant text null,
  
  -- 主键和约束
  constraint matching_rule_pkey primary key (id),
  constraint matching_rule_user_id_id_key unique (user_id, id),
  
  -- 外键约束
  constraint matching_rule_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade,
  constraint matching_rule_main_category_fk foreign key (user_id, t_main_category_id) references main_category (user_id, id) on update cascade on delete set null,
  constraint matching_rule_sub_category_fk foreign key (user_id, t_sub_category_id) references sub_category (user_id, id) on update cascade on delete set null,
  constraint matching_rule_budget_type_fk foreign key (user_id, t_budget_type_id) references budget_type (user_id, id) on update cascade on delete set null,
  
  -- 检查约束
  constraint matching_rule_amount_range_check check (
    f_original_amount_ge is null or 
    f_original_amount_le is null or 
    f_original_amount_ge <= f_original_amount_le
  )
) tablespace pg_default;