create table public.sub_category (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  main_category_id bigint not null,
  label text not null,
  icon text not null,
  back_color text not null,
  fore_color text not null,
  budget_type_id bigint null,
  constraint sub_category_pkey primary key (id),
  constraint sub_category_user_id_id_key unique (user_id, id),
  constraint sub_category_user_id_main_category_id_label_key unique (user_id, main_category_id, label),
  constraint fk_sub_budget foreign KEY (user_id, budget_type_id) references budget_type (user_id, id) on update CASCADE on delete set null,
  constraint fk_sub_main foreign KEY (user_id, main_category_id) references main_category (user_id, id) on update CASCADE on delete CASCADE,
  constraint sub_category_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists sub_category_user_id_main_category_id_idx on public.sub_category using btree (user_id, main_category_id) TABLESPACE pg_default;

create index IF not exists sub_category_user_id_budget_type_id_idx on public.sub_category using btree (user_id, budget_type_id) TABLESPACE pg_default;